### ISSUE TITLE
Browser Extension Error (v 1.1.0)

### ISSUE THREAD

**Issue by DeadLyBro** [moonlight-mod/moonlight#124]
I'm followed extension steps but when I try to open "Moonbase" section from "User Settings" it drops error; 

Screenshot
![Image](https://github.com/user-attachments/assets/15c21fc8-7e77-41c4-8307-65e5f46f71de)

**Comment by NotNite** [comment]
This error was unrelated to the browser extension - Discord broke some things and we were waiting for a stable release to update moonlight. Seems like you've got it.

Update and rebuild the extension and things should work now. Feel free to reopen if you have any issues!

**Comment by DeadLyBro** [comment]
> This error was unrelated to the browser extension - Discord broke some things and we were waiting for a stable release to update moonlight. Seems like you've got it.
> 
> Update and rebuild the extension and things should work now. Feel free to reopen if you have any issues!

Working now, thanks.

**Comment by DeadLyBro** [comment]
Actually I have one problem. When I tried to enable something and save it, it say "you need to restart application" right? When I reload tab, it kick me from account and I need to re-login. 

@NotNite Thanks for answering & fixing my issue. (btw I don't have permission to reopen issue.)

**Comment by NotNite** [comment]
Interesting - I'll look into that later.

**Comment by DeadLyBro** [comment]
> Interesting - I'll look into that later.

Ok np, I need to sleep, good night.
