### ISSUE TITLE
extensions should fail gracefully

### ISSUE THREAD

**Issue by jane0009** [moonlight-mod/moonlight#25]
ran into an unrelated issue with an extension; upon opening, discord refuses to load *at all*. in order to fix the issue, i have to go and manually edit the settings file to disable the errored extension.

i think it would be better for ux if when an extension throws any sort of fatal error, it's simply skipped over and not loaded. (i'm unsure if this is even possible with the current architecture though)

**Comment by NotNite** [comment]
Fixed in https://github.com/moonlight-mod/moonlight/commit/dc18124532f936c0ffde913897125fed2faba964
