### ISSUE TITLE
Malware detected in moonlight installer

### ISSUE THREAD

**Issue by dudulecode** [moonlight-mod/moonlight#33]
Hey, I don't know if it's a false positive or not but I checked Moonlight Installer (Windows Version) and VirusTotal detected a malware in it.

There's a screenshot of my scan:
![image](https://github.com/moonlight-mod/moonlight/assets/156611137/d9d57395-fce7-4bd9-9cb6-9b35d9cb0325)

**Comment by Cynosphere** [comment]
Only 4 false positives and they're all just generic labels, impressive

**Comment by dudulecode** [comment]
alright sorry, I was just wondering why it was detected as a malware by only 4 anti-viruses.
