### ISSUE TITLE
Rethink how we should approach a standalone desktop app

### ISSUE THREAD

**Issue by NotNite** [moonlight-mod/moonlight#64]
Right now moonlight has support for OpenAsar and a "moonlight desktop" which doesn't exist yet. The primary motivation for having a desktop moonlight app is for better Linux support. Let's brainstorm some questions:

- Should we make a moonlight desktop?
  - The primary goal is better Linux support.
- If we are going to make a moonlight desktop, would we do it all ourselves?
  - Seems like wasted effort. We could perhaps PR moonlight support into another app or fork an app.
  - I currently use [Vesktop](https://github.com/Vencord/Vesktop) on my laptop, but it seems pretty well engrained into the Vencord ecosystem. 
- Should that moonlight desktop code stay?
  - It seems to just add extra complexity for no use right now, but it might make it easier for someone else to integrate moonlight into a standalone app.

**Comment by NotNite** [comment]
I've made a fork of Discord's Electron [here](https://github.com/NotNite/electron) and compiled it without the getUserMedia patch. This is the biggest "better Linux support" item, so we can play with that and see if it goes anywhere.

If it does go somewhere, we'll move the fork into this repository and adopt it as an "official" project, putting the built Electron as a release. We can't build Electron in CI since it doesn't have enough time/disk/memory, so it'll just have to be a "trust us bro" situation. Then, we can write a shell script to download Discord and merge our Electron into it.

**Comment by adryd325** [comment]
We have rocketship that fulfills this goal!
