### ISSUE TITLE
Warn about extensions with duplicate `id`s

### ISSUE THREAD

**Issue by Cynosphere** [moonlight-mod/moonlight#93]
Compare metadata, show path of the two if minimal differences (e.g. version), otherwise something along the lines of "Extensions x and y share the same ID of z"

Should probably be console only since its more likely to happen in development from copy pasting, as its something that wouldn't happen on the main repo

Maybe also an indicator of what repo its from on the extension card (and maybe a different icon for the main repo)

**Comment by NotNite** [comment]
Completed in https://github.com/moonlight-mod/moonlight/commit/779b424caed3f03cc9e9e603c8c8b8637f9539fe, I decided to only log the extension ID since there's only two places it could be (extension install folder and search paths)
